# Generated by Django 5.0.7 on 2024-08-23 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='image',
            field=models.ImageField(default='profils/default_profile.webp', upload_to='profils/'),
        ),
    ]
