# Generated by Django 5.0.7 on 2024-08-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profil_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='tag_skills',
            field=models.ManyToManyField(blank=True, related_name='prof_skill', to='users.skill'),
        ),
    ]
