# Generated by Django 5.0.7 on 2024-08-10 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_review_project_alter_review_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tag',
            field=models.ManyToManyField(blank=True, to='project.tag'),
        ),
    ]
