# Generated by Django 5.0.7 on 2024-08-18 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_project_tag_alter_review_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
