# Generated by Django 5.0.7 on 2024-08-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_alter_project_image_alter_review_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default='images/it.png', null=True, upload_to='projects/'),
        ),
    ]
