# Generated by Django 5.0.7 on 2024-08-23 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_project_user_review_user_alter_review_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='value',
            field=models.CharField(choices=[('+', 'ijobiy'), ('-', 'salbiy')], max_length=50),
        ),
    ]
