# Generated by Django 5.0.7 on 2024-08-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_alter_review_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='value',
            field=models.CharField(choices=[('+', 'ijobiy'), ('-', 'salbiy')], max_length=50),
        ),
    ]
