# Generated by Django 5.0.7 on 2024-09-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0021_alter_comment_user_alter_review_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='value',
            field=models.CharField(choices=[('-', 'salbiy'), ('+', 'ijobiy')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
